- hosts: server1, server2, server3
  remote_user: isucon
  strategy: free

  tasks:    
  - name: create nginx digest
    shell: |
      alp ltsv -c alp.yml
    register: nginx_out
    when: "(server_no) == (nginx_server_no)"

  # - name: output nginx digest
  #   debug:
  #     msg: "{{ nginx_out.stdout }}"
  #   when: "(server_no) == (nginx_server_no)"

  - name: write to file
    copy:
      content: "{{ nginx_out.stdout }}"
      dest: /tmp/nginx_digest.txt
      backup: yes
    when: "(server_no) == (nginx_server_no)"
    delegate_to: localhost

  - name: create mysql digest
    shell: |
      # sudo pt-query-digest /var/log/mysql/mysql-slow.log
      # sudo pt-query-digest /var/log/mysql/mariadb-slow.log
      sudo mysqldumpslow -s t /var/log/mysql/mysql-slow.log
    become: true
    register: mysql_out
    when: "(server_no) == (db_server_no)"

  # - name: output mysql digest
  #   debug:
  #     msg: "{{ mysql_out.stdout }}"
  #   when: "(server_no) == (db_server_no)"

  - name: write to file
    copy:
      content: "{{ mysql_out.stdout }}"
      dest: /tmp/mysql_digest.txt
      backup: yes
    when: "(server_no) == (db_server_no)"
    delegate_to: localhost

  - name: create sqlite digest
    shell: |
      python3 summarize_sqlite.py /home/isucon/tmp/sqlite.log
    become: true
    register: sqlite_out
    when: "(server_no) == (app_server_no)"

  - name: write to file
    copy:
      content: "{{ sqlite_out.stdout }}"
      dest: /tmp/sqlite_digest.txt
      backup: yes
    when: "(server_no) == (app_server_no)"
    delegate_to: localhost