- hosts: server1, server2, server3
  remote_user: isucon
  strategy: linear

  tasks:    
  - name: restart all services
    shell: |
      cd ~/webapp/go/
      go build -o isucondition .
      sudo rm -f /var/log/nginx/access.log
      sudo rm -f /var/log/mysql/mysql-slow.log
      sudo rm -f /home/isucon/tmp/sqlite.log
      sudo systemctl restart nginx mysql isuports.service
    become: true
