- name: Add apt repository
  shell: |
    add-apt-repository ppa:longsleep/golang-backports -y
    apt update
    apt install golang-go -y
  become: true

- name: Update .bashrc
  shell: |
    echo export PATH=/usr/lib/go/bin:$PATH >> ~/.bashrc
    echo export GOROOT=/usr/lib/go >> ~/.bashrc