- hosts: server1
  remote_user: isucon
  strategy: linear

  tasks:
  - name: pause
    pause:
      seconds: 20
  
  - name: top
    shell: |
      top -b -n 1
    register: top_out
    when: "(server_no) == (nginx_server_no)"
    
  - name: write to file
    copy:
      content: "{{ top_out.stdout }}"
      dest: /tmp/top.txt
      backup: yes
    when: "(server_no) == (nginx_server_no)"
    delegate_to: localhost

  # - name: pprof
  #   shell: |
  #     nohup /home/isucon/local/go/bin/go tool pprof -http=0.0.0.0:8080 /home/isucon/webapp/go/isucondition http://localhost:6060/debug/pprof/profile &
  

