- name: Copy private key and public key to servers
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: isucon
    group: isucon
    mode: "{{ item.mode }}"
    backup: yes
  with_items:
  - { src: ~/.ssh/isucon_id_rsa, dest: ~/.ssh/id_rsa, mode: '0600' }
  - { src: ~/.ssh/isucon_id_rsa.pub, dest: ~/.ssh/id_rsa.pub, mode: '0644' }

- name: add public key to authorized_keys
  shell: |
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

- name: Turn off strict host key checking when accessing github
  copy:
    src: .ssh/config
    dest: ~/.ssh/config
    owner: isucon
    group: isucon
    mode: 0700
    backup: yes
  become: yes
  become_user: isucon

- name: Deploy .gitconfig
  copy:
    src: .gitconfig
    dest: ~/.gitconfig
    owner: isucon
    group: isucon
    mode: 0700
    backup: yes
  become: yes
  become_user: isucon

- name: clone repo
  shell: |
    git init
    git remote add origin https://github.com/itohdak/{{ git_repo_name }}.git
    git checkout -b main
    git fetch --all
    git reset --hard origin/main