- name: Install slp
  ansible.builtin.get_url:
    url: https://github.com/tkuchiki/slp/releases/download/v0.2.0/slp_linux_amd64.tar.gz
    dest: /tmp/slp_linux_amd64.tar.gz

- name: Unarchive and deploy slp
  ansible.builtin.unarchive:
    src: /tmp/slp_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
  become: true

- name: Install alp
  ansible.builtin.get_url:
    url: https://github.com/tkuchiki/alp/releases/download/v1.0.21/alp_linux_amd64.tar.gz
    dest: /tmp/alp_linux_amd64.tar.gz

- name: Unarchive and deploy alp
  ansible.builtin.unarchive:
    src: /tmp/alp_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
  become: true

- name: Install pprotein
  ansible.builtin.get_url:
    url: https://github.com/kaz/pprotein/releases/download/v1.2.3/pprotein_1.2.3_linux_amd64.tar.gz
    dest: /tmp/pprotein_1.2.3_linux_amd64.tar.gz

- name: Unarchive and deploy pprotein
  ansible.builtin.unarchive:
    src: /tmp/pprotein_1.2.3_linux_amd64.tar.gz
    dest: /home/isucon
    remote_src: true
  become: true

- name: Deploy pprotein service
  ansible.builtin.copy:
    src: etc/systemd/system/pprotein.service
    dest: /etc/systemd/system/pprotein.service
  become: true
  when: inventory_hostname in groups['pprotein']

- name: Enable and start pprotein service
  ansible.builtin.systemd_service:
    state: started
    name: pprotein
    enabled: true
    daemon_reload: true
  become: true
  when: inventory_hostname in groups['pprotein']

- name: Deploy pprotein-agent service
  ansible.builtin.copy:
    src: etc/systemd/system/pprotein-agent.service
    dest: /etc/systemd/system/pprotein-agent.service
  become: true
  when: inventory_hostname in groups['webapp']

- name: Enable and start pprotein-agent service
  ansible.builtin.systemd_service:
    state: started
    name: pprotein-agent
    enabled: true
    daemon_reload: true
  become: true
  when: inventory_hostname in groups['webapp']

- name: Deploy targets.json
  ansible.builtin.copy:
    src: targets.json
    dest: /home/isucon/data/targets.json
  become: true
  when: inventory_hostname in groups['pprotein']

- name: Deploy alp.yaml
  ansible.builtin.copy:
    src: alp.yaml
    dest: /home/isucon/data/alp.yml
  become: true
  when: inventory_hostname in groups['pprotein']

- name: Copy ansible files
  ansible.builtin.copy:
    src: ansible_frontend
    dest: /home/isucon/
    owner: isucon
    group: isucon
    mode: '0777'
  when: inventory_hostname in groups['pprotein']

- name: Install and setup ansible
  ansible.builtin.shell: |
    # apt update
    # apt install software-properties-common
    apt-add-repository --yes --update ppa:ansible/ansible
    apt install -y ansible
    echo 192.168.0.11 s1 >> /etc/hosts
    echo 192.168.0.12 s2 >> /etc/hosts
    echo 192.168.0.13 s3 >> /etc/hosts
  become: true
  when: inventory_hostname in groups['pprotein']

- name: Git clone
  ansible.builtin.shell: |
    git clone https://github.com/itohdak/isucon_ansible.git
  when: inventory_hostname in groups['pprotein']

- name: Deploy ansible-frontend service
  ansible.builtin.copy:
    src: etc/systemd/system/ansible-frontend.service
    dest: /etc/systemd/system/ansible-frontend.service
  become: true
  when: inventory_hostname in groups['pprotein']

- name: Enable and start ansible-frontend service
  ansible.builtin.systemd_service:
    state: started
    name: ansible-frontend
    enabled: true
    daemon_reload: true
  become: true
  when: inventory_hostname in groups['pprotein']
