- hosts: all
  remote_user: isucon
  tasks:
    - import_role:
        name: general
        tasks_from: main
- hosts: all
  remote_user: isucon
  tasks:
    - import_role:
        name: repo
        tasks_from: setup
- hosts: all
  remote_user: isucon
  tasks:
    - import_role:
        name: pprotein
        tasks_from: main
